import './globals.css';

import type { Metadata } from 'next';
import { Rajdhani } from 'next/font/google';

const rajdhani = Rajdhani({
  weight: ['500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-family-rajdhani',
});

export const metadata: Metadata = {
  title: 'FullstacksJS - Community',
  authors: [{ name: 'ASafaeirad', url: 'https://github.com/ASafaeirad/' }],
  description: 'Generated by create next app',
  keywords: [
    'community',
    'telegram',
    'کانال برنامه نویسی',
    'کانال تلگرام',
    'فول‌استکس',
  ].join(','),
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html
      lang="en"
      className={`${rajdhani.variable} bg-dark-0 leading-normal text-light-0`}
    >
      <body className="text-base">
        <div className="container flex flex-col gap-24 py-8 mobile:gap-40 tablet:py-40">
          {/* <Header />
          <Hero />
          <HeroMobile />
          <Separator /> */}
          {children}
          {/* <Separator />
          <Social /> */}
        </div>
      </body>
    </html>
  );
}
